# Site settings
title: "YIAKI 株式会社"
tagline: "広く、見る。"
author: 
first_button_text: 'Find out more'
first_button_url: '#about'
header_img: /img/header.jpg
home_menu_text: YIAKI.JP
description: "文案1"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Theme customization
primary: '#F05F40'
dark: '#222'

# Contact details
email: info@yiaki.jp
telephone_number: 
whatsapp_number: 
twitter_username:
github_username:
instagram_username: 
facebook_username: 
linkedin_username: 

# Data collections
collections:
  blocks:
    output: false
  # gallery:
  #   output: false

# Build settings
markdown: kramdown

exclude:
  - serve
  - README.md
  - LICENCE

